### ISSUE TITLE
Delete VM is not working

### ISSUE THREAD

**Issue by puneet101** [Azure-Samples/compute-java-manage-vm#14]
Getting this error message:

The api-version '2016-03-30' is invalid. The supported versions are '2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.: The api-version '2016-03-30' is invalid. The supported versions are '2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
    at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:521)
    at com.microsoft.azure.AzureClient.access$000(AzureClient.java:34)
    at com.microsoft.azure.AzureClient$3.call(AzureClient.java:281)
    at com.microsoft.azure.AzureClient$3.call(AzureClient.java:278)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
    at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
    at rx.Subscriber.setProducer(Subscriber.java:211)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
    at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
    at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
    at rx.Observable.unsafeSubscribe(Observable.java:9861)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:9861)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.Observable.subscribe(Observable.java:9957)
    at rx.Observable.subscribe(Observable.java:9924)
    at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:479)
    at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.deleteByGroup(GroupableResourcesImpl.java:60)

**Comment by anuchandy** [comment]
@puneet101 thanks for reporting, let me investigate.

**Comment by anuchandy** [comment]
I am unable to repro this, so to debug this further can you turn on the log and share the log, log level `HttpLoggingInterceptor.Level.BASIC` is sufficient which can be set as below:

```java
            Azure azure = Azure
                    .configure()
                    .withLogLevel(HttpLoggingInterceptor.Level.BASIC)
                    .authenticate(credFile)
                    .withDefaultSubscription();
```

**Comment by puneet101** [comment]
Oct 27, 2016 10:28:20 PM okhttp3.internal.Platform log
INFO: --> GET https://management.azure.com/subscriptions/1945149d-d86e-4767-b400-f03a7eb98cf0/resourceGroups/WORKSPOT-RG/providers/Microsoft.Compute/virtualMachines/azuredemo-0001?api-version=2016-03-30 http/1.1
Oct 27, 2016 10:28:20 PM okhttp3.internal.Platform log
INFO: <-- 200 OK https://management.azure.com/subscriptions/1945149d-d86e-4767-b400-f03a7eb98cf0/resourceGroups/WORKSPOT-RG/providers/Microsoft.Compute/virtualMachines/azuredemo-0001?api-version=2016-03-30 (75ms, unknown-length body)
Oct 27, 2016 10:28:20 PM okhttp3.internal.Platform log
INFO: --> DELETE https://management.azure.com/subscriptions/1945149d-d86e-4767-b400-f03a7eb98cf0/resourceGroups/%2Fsubscriptions%2F1945149d-d86e-4767-b400-f03a7eb98cf0%2FresourceGroups%2FWORKSPOT-RG%2Fproviders%2FMicrosoft.Compute%2FvirtualMachines%2Fazuredemo-0001/providers/Microsoft.Compute/virtualMachines/WORKSPOT-RG?api-version=2016-03-30 http/1.1 (0-byte body)
Oct 27, 2016 10:28:20 PM okhttp3.internal.Platform log
INFO: <-- 400 Bad Request https://management.azure.com/subscriptions/1945149d-d86e-4767-b400-f03a7eb98cf0/resourceGroups/%2Fsubscriptions%2F1945149d-d86e-4767-b400-f03a7eb98cf0%2FresourceGroups%2FWORKSPOT-RG%2Fproviders%2FMicrosoft.Compute%2FvirtualMachines%2Fazuredemo-0001/providers/Microsoft.Compute/virtualMachines/WORKSPOT-RG?api-version=2016-03-30 (25ms, 267-byte body)
22:28:20.909 [main] DEBUG c.w.connector.azure.AzureManager - Exception: The api-version '2016-03-30' is invalid. The supported versions are '2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
com.microsoft.azure.CloudException: The api-version '2016-03-30' is invalid. The supported versions are '2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.: The api-version '2016-03-30' is invalid. The supported versions are '2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:521)
	at com.microsoft.azure.AzureClient.access$000(AzureClient.java:34)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:281)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:278)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:479)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.GroupableResourcesImpl.deleteByGroup(GroupableResourcesImpl.java:60)
	at com.workspot.connector.azure.AzureManager.deleteVM(AzureManager.java:1087)
	

We are using:

	        VirtualMachine machine = azureInstance.virtualMachines().getById(vmUuid);
		String resourceGroup = machine.resourceGroupName();
		azureInstance.virtualMachines().deleteByGroup(vmUuid, resourceGroup);

**Comment by puneet101** [comment]
azureInstance.virtualMachines().deleteById(vmUuid);
seems to be working.

Can you share an example of 
deleteByGroup(arg1, arg2)

**Comment by anuchandy** [comment]
Can you confirm you are using this method like below?

e.g. deleteByGroup("WORKSPOT-RG", "azuredemo-0001");

i.e. the first param is resource group name and second is virtual machine name, not id.

**Comment by puneet101** [comment]
Yes, we were not using it correctly. False Alarm.

Is there a way to populate arg1, arg2 in the docs auto-generated to help avoid such mistakes. Thanks!

**Comment by puneet101** [comment]
BTW, is there a way to delete VM w/ all it's dependencies? Looks like VM-delete does not delete all the internal resources like OS disk and network interface are not deleted. 

Is there a sample to understand how to delete a VM with all the internal resources? Thanks!

**Comment by anuchandy** [comment]
Today the easiest way to handle this is - use one resource group per virtual machine and it's associated resources and delete the resource group when you want to clean up. 

There is no option in the virtual machine delete API where we can specify a flag for this, i assume the reason is - resources such as NIC, subnet, storage account etc are not `internal resources`, they are top level resources that can exists without a virtual machine.

Regarding `deleteByGroup` - below is the comment for deleting a resource (e.g. VM) from a resource group, i don't think we use param names such as arg1, arg2, am i missing something?
 
```
void deleteByGroup(String groupName, String name)
  Deletes a resource from Azure, identifying it by its name and its resource group.
  Parameters:
  groupName - The group the resource is part of
  name - The name of the resource
```
