### ISSUE TITLE
Issue with vm.capture API

### ISSUE THREAD

**Issue by puneet101** [Azure-Samples/compute-java-manage-vm#9]
vm.capture("name", true); 
is failing with error:
vhdPrefix is required and cannot be null.
    at com.microsoft.rest.Validator.validate(Validator.java:75)
    at com.microsoft.azure.management.compute.implementation.VirtualMachinesInner.capture(VirtualMachinesInner.java:185)
    at com.microsoft.azure.management.compute.implementation.VirtualMachineImpl.capture(VirtualMachineImpl.java:211)

ARM API shows capture call with 3 parameters:

{
  "vhdPrefix": "(string)",
  "destinationContainerName": "(string)",
  "overwriteVhds": "(boolean)"
}

Any idea why the java SDK is not showing the 3rd parameter? 

We are using the 1.0.0-beta2 jar.

**Comment by anuchandy** [comment]
@puneet101 thanks for reporting this, this is a bug, will push the fix and let you know when the snapshots are out.

**Comment by puneet101** [comment]
Great, thanks! 
Are there any workarounds or other options to create an image? What's the tentative timeline for new snapshots?
